### ISSUE TITLE
Spaghetti code

### ISSUE THREAD

**Issue by jakub-trzebiatowski** [raspofabs/olddodsrc#1]
All the code ind DOD version of the game is contained in one file. Nearly all the code is contained in three giant functions which modify global state a lot. Does it need to be like that? The book says that DOD can be very readable, and I can't see that in this code...

**Comment by raspofabs** [comment]
1. this is a codebase that is meant to mirror reality where possible, so even though DOD tends towards more readable code, it doesn't guarantee it. In this case, I've not allowed any time for "cleaning up" the DOD code, only the OOP code so far as unclean OOP is totally inpenetrable.
2. those three giant functions are linear. There is no spaghetti.

I think if you try to add a feature to both code bases (not something trivial) then you will see that the OOP code, though on the surface is more readable, hides what is going on and so introduces longer dev time trying to find all the places where you need to change or add a feature to the code.

I'll leave this bug open and add it as a client request for the next "design update", along the lines of "external team requires a cleaned up version of the code for porting to uFruit devices."
